export const slideData = [
    {
        title: "Thunderbolts: Biệt Đội Sấm Sét",
        aliasTitle: "Thunderbolts",
        detailUrl: "/phim/thunderbolts-biet-doi-sam-set.rfDhoxup",
        bgImage: "https://static.nutscdn.com/vimg/1920-0/8075260038eecb4c9684956a174180a5.jpg",
        watchUrl: "/xem-phim/thunderbolts-biet-doi-sam-set.rfDhoxup",
        imdb: "7.6",
        age: "T16",
        year: "2025",
        duration: "2h 10m",
        genres: [
            { name: "Hành Động", url: "/the-loai/hanh-dong.2xCjTG" },
            { name: "Chiếu Rạp", url: "/the-loai/chieu-rap.3679nF" },
            { name: "Siêu Anh Hùng", url: "/the-loai/sieu-anh-hung.OW2M9i" },
            { name: "Marvel", url: "/the-loai/marvel.QriAOn" },
            { name: "Kỳ Ảo", url: "/the-loai/ky-ao.gVRG25" },
            { name: "Phiêu Lưu", url: "/the-loai/phieu-luu.wca3Bp" },
        ],
        description: `Ai trong team này cũng từng làm việc ác, giờ là lúc làm việc ác cùng nhau...`,
        thumbnail: "https://static.nutscdn.com/vimg/1920-0/8075260038eecb4c9684956a174180a5.jpg",
    },
    {
        title: "Thunderbolts: Biệt Đội Sấm Sét",
        aliasTitle: "Thunderbolts",
        detailUrl: "/phim/thunderbolts-biet-doi-sam-set.rfDhoxup",
        bgImage: "https://static.nutscdn.com/vimg/1920-0/8075260038eecb4c9684956a174180a5.jpg",
        watchUrl: "/xem-phim/thunderbolts-biet-doi-sam-set.rfDhoxup",
        imdb: "7.6",
        age: "T16",
        year: "2025",
        duration: "2h 10m",
        genres: [
            { name: "Hành Động", url: "/the-loai/hanh-dong.2xCjTG" },
            { name: "Chiếu Rạp", url: "/the-loai/chieu-rap.3679nF" },
            { name: "Siêu Anh Hùng", url: "/the-loai/sieu-anh-hung.OW2M9i" },
            { name: "Marvel", url: "/the-loai/marvel.QriAOn" },
            { name: "Kỳ Ảo", url: "/the-loai/ky-ao.gVRG25" },
            { name: "Phiêu Lưu", url: "/the-loai/phieu-luu.wca3Bp" },
        ],
        description: `Ai trong team này cũng từng làm việc ác, giờ là lúc làm việc ác cùng nhau...`,
        thumbnail: "https://static.nutscdn.com/vimg/1920-0/8075260038eecb4c9684956a174180a5.jpg",
    },
    // thêm dữ liệu nếu cần
];